import { NextPage } from "next";
import Head from "next/head";

import Footer from "@/components/footer/footer";

const ShopDetail: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ちかれす - 店舗詳細</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
      <Footer />
    </div>
  );
};

export default ShopDetail;
