import { Button, Text } from "@chakra-ui/react";
import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { useGeolocation } from "@/hooks/useGeolocation";

const Index: NextPage = () => {
  const { currentPos, errorMessage, getPos } = useGeolocation();

  return (
    <div>
      <Head>
        <title>レストラン検索アプリ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/test">go to test</Link>
      <div>
        <Button onClick={() => getPos()}>geo</Button>
      </div>
      <Text>
        {currentPos
          ? `緯度: ${currentPos.coords.latitude} 経度: ${currentPos.coords.longitude}`
          : "位置不明"}
      </Text>
      {errorMessage ? errorMessage : null}
    </div>
  );
};

export default Index;
