import { Box, Spinner } from "@chakra-ui/react";
import { useAtom } from "jotai";
import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import useSWR from "swr";

import { ShopFetchResult } from "@/@types/api/resultsType";
import SearchFormMemo from "@/components/form/searchForm";
import ShopCard from "@/components/shopCard/shopCard";
import fetcher from "@/lib/fetcher";
import { searchParamAtom } from "@/store/searchParamAtom";

const Index: NextPage = () => {
  const [searchParam, setSearchParam] = useAtom(searchParamAtom);

  console.log(searchParam);

  const { data: shopData } = useSWR<ShopFetchResult>(
    searchParam ? ["/api/shop", searchParam] : null,
    fetcher,
  );

  return (
    <div>
      <Head>
        <title>レストラン検索アプリ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/test">go to test</Link>
      <SearchFormMemo />
      <Box>
        {shopData ? (
          shopData.results.shop.map((shop) => (
            <ShopCard
              key={shop.name}
              name={shop.name}
              access={shop.access}
              address={shop.address}
              src={shop.photo.pc.l}
            />
          ))
        ) : (
          <Spinner />
        )}
      </Box>
    </div>
  );
};

export default Index;
